custom:
  bert_base_path: chinese-roberta-wwm-ext-large
  cnhuhbert_base_path: chinese-hubert-base
  device: cpu
  is_half: false
  t2s_weights_path: "\u70DF\u7EEF_JA/\u70DF\u7EEF_JA-e10.ckpt"
  version: v2
  vits_weights_path: "\u70DF\u7EEF_JA/\u70DF\u7EEF\
    _JA_e10_s500_l32.pth"
v1:
  bert_base_path: chinese-roberta-wwm-ext-large
  cnhuhbert_base_path: chinese-hubert-base
  device: cpu
  is_half: false
  t2s_weights_path: s1bert25hz-2kh-longer-epoch=68e-step=50232.ckpt
  version: v1
  vits_weights_path: s2G488k.pth
v2:
  bert_base_path: chinese-roberta-wwm-ext-large
  cnhuhbert_base_path: chinese-hubert-base
  device: cpu
  is_half: false
  t2s_weights_path: gsv-v2final-pretrained/s1bert25hz-5kh-longer-epoch=12-step=369668.ckpt
  version: v2
  vits_weights_path: gsv-v2final-pretrained/s2G2333k.pth
v3:
  bert_base_path: chinese-roberta-wwm-ext-large
  cnhuhbert_base_path: chinese-hubert-base
  device: cpu
  is_half: false
  t2s_weights_path: s1v3.ckpt
  version: v3
  vits_weights_path: s2Gv3.pth
v4:
  bert_base_path: chinese-roberta-wwm-ext-large
  cnhuhbert_base_path: chinese-hubert-base
  device: cpu
  is_half: false
  t2s_weights_path: s1v3.ckpt
  version: v4
  vits_weights_path: gsv-v4-pretrained/s2Gv4.pth
